parameters:
  oxidesales.graphqlstorefront.depends_on_modules: [ 'oe_graphql_base' ]

imports:
  - { resource: src/Shared/services.yaml }
  - { resource: src/Action/services.yaml }
  - { resource: src/Address/services.yaml }
  - { resource: src/Attribute/services.yaml }
  - { resource: src/Banner/services.yaml }
  - { resource: src/Basket/services.yaml }
  - { resource: src/Category/services.yaml }
  - { resource: src/Contact/services.yaml }
  - { resource: src/Content/services.yaml }
  - { resource: src/Country/services.yaml }
  - { resource: src/Currency/services.yaml }
  - { resource: src/Customer/services.yaml }
  - { resource: src/DeliveryMethod/services.yaml }
  - { resource: src/File/services.yaml }
  - { resource: src/Framework/services.yaml }
  - { resource: src/Link/services.yaml }
  - { resource: src/Manufacturer/services.yaml }
  - { resource: src/NewsletterStatus/services.yaml }
  - { resource: src/Order/services.yaml }
  - { resource: src/Payment/services.yaml }
  - { resource: src/Product/services.yaml }
  - { resource: src/Promotion/services.yaml }
  - { resource: src/Review/services.yaml }
  - { resource: src/Translation/services.yaml }
  - { resource: src/Vendor/services.yaml }
  - { resource: src/Voucher/services.yaml }
  - { resource: src/WishedPrice/services.yaml }

services:
  _defaults:
    autowire: true
    public: false

  OxidEsales\Eshop\Core\Registry:
    class: OxidEsales\Eshop\Core\Registry
    public: true

  OxidEsales\Eshop\Core\Language:
    factory: [ '@OxidEsales\Eshop\Core\Registry', 'getLang' ]
    public: true
