services:
  _defaults:
    autowire: true
    public: false

  OxidEsales\GraphQL\Storefront\Shared\Infrastructure\Basket:
    public: true

  OxidEsales\GraphQL\Storefront\Shared\Infrastructure\LanguageInfrastructure:
    public: true

  OxidEsales\GraphQL\Storefront\Shared\Infrastructure\ListConfiguration:
    arguments:
      $map: { }
    public: true

  OxidEsales\GraphQL\Storefront\Shared\Infrastructure\OxNewFactoryInterface:
    class: OxidEsales\GraphQL\Storefront\Shared\Infrastructure\OxNewFactory
    public: true

  OxidEsales\GraphQL\Storefront\Shared\Infrastructure\RepositoryInterface:
    class: OxidEsales\GraphQL\Storefront\Shared\Infrastructure\Repository
    public: true
