services:
  _defaults:
    autowire: true
    public: false

  OxidEsales\GraphQL\Storefront\Customer\Service\CustomerInterface:
    class: OxidEsales\GraphQL\Storefront\Customer\Service\Customer
    public: true
    arguments:
      TheCodingMachine\GraphQLite\Security\AuthorizationServiceInterface: '@OxidEsales\GraphQL\Base\Service\Authorization'

  OxidEsales\GraphQL\Storefront\Customer\Service\CustomerRegisterInput:
    public: true

  OxidEsales\GraphQL\Storefront\Customer\Service\PasswordInterface:
    class: OxidEsales\GraphQL\Storefront\Customer\Service\Password
    arguments:
      TheCodingMachine\GraphQLite\Security\AuthenticationServiceInterface: '@OxidEsales\GraphQL\Base\Service\Authentication'

  OxidEsales\GraphQL\Storefront\Customer\Service\RelationService:
    public: true
