# {{ $ids := "oe_graphql_storefront" }}ids: {{ print $ids }}
# {{ $org := "oxid-esales" }}organisation: {{ print $org }}
# {{ $name := "graphql-storefront" }}name: {{ print $name }}
prepare_shop:
    specific: &specific_matrix
        php: '["8.2"]'
        mysql: '["8.0"]'
    git:
        shop_ref: '{{ .Data.global.git.default_ref }}'
    custom_ini:
        xdebug: 'xdebug.mode=debug,profile,coverage'
    composer:
        transform: |
            {
                "require-dev": {
                    "codeception/module-rest": "^3.3",
                    "codeception/module-phpbrowser": "^3.0",
                    "codeception/c3": "^2.9",
                    "oxid-esales/twig-component": "{{ .Data.global.composer.dev_ref }}",
                    "oxid-esales/twig-admin-theme": "{{ .Data.global.composer.dev_ref }}",
                    "oxid-esales/apex-theme": "{{ .Data.global.composer.dev_ref }}",
                    "oxid-esales/oxideshop-demodata-ce": "dev-master"
                },
                "config":{
                    "allow-plugins":{
                      "oxid-esales/oxideshop-composer-plugin": true,
                      "oxid-esales/oxideshop-unified-namespace-generator": true,
                        "codeception/c3": true
                    }
                }
            }

install_module:
    matrix:
        testplan: '["-"]'
    max_parallel: 1
    cache:
        prefix: &install_module_prefix 'moduleInstallation-ce-{{ .Github.SHA }}-{{ .Github.RunID }}'
    ids: &ids '{{ print $ids }}'
    git:
        module:
            url: '{{ .Github.Repository }}'
            ref: '{{ .Github.RefName }}'
    package_name: &package_name '{{ print $org }}/{{ print $name }}'
    path: *ids
    activate: |
        oe_graphql_base
        {{ print $ids }}
    custom_script: |
        perl -pi -e 'print "SetEnvIf Authorization \"(.*)\" HTTP_AUTHORIZATION=\$1\n\n" if $. == 1' source/source/.htaccess
        sed -i 's/<?php/<?php\n\nrequire(__DIR__ . "\/..\/c3.php");/' source/source/bootstrap.php
    custom_script_container:
        bin/oe-console oe:setup:demodata

phpunit:
    matrix:
        testplan: '["~/defaults/module_phpunit_unit.yml","~/defaults/module_phpunit_integration.yml"]'
    load_shop: *install_module_prefix

runtest:
    matrix:
        testplan: 'skip'

codeception:
    matrix:
        testplan: '
      [
        "~/graphql-storefront-basket.yml",
        "~/graphql-storefront-other.yml"
      ]'
    load_shop: *install_module_prefix
    container:
        options: '-e SELENIUM_SERVER_HOST=selenium -e BROWSER_NAME=chrome -e ACTIVE_THEME=apex -e XDEBUG_MODE=coverage -e THEME_ID=apex'
    suite: 'Acceptance'

phpcs_tests:
    matrix:
        testplan: '["~/defaults/module_codeception_Acceptance_71x.yml"]'
    load_shop: *install_module_prefix
    additional_options: '--standard=tests/phpcs.xml --report=json --report-file=tests/reports/phpcs.report.json'

styles:
    matrix:
        <<: *specific_matrix
        testplan: '["-"]'
    load_shop: *install_module_prefix
    path: "{{ print $ids }}"
    module_ids: *ids

sonarcloud:
    matrix:
        <<: *specific_matrix
        testplan: '["-"]'
    project_key: 'OXID-eSales_graphql-storefront-module'
    project_name: *package_name
    parameters: |
        -Dsonar.language=php
        -Dsonar.scm.provider=git
        -Dsonar.sources=src
        -Dsonar.tests=tests

finish:
    slack_title: 'Module graphql-storefront-module on {{ .Github.Repository }} by {{ .Github.Actor }}'
