# {{ $order := "04" }}order: {{ print $order }}
# {{ $org := "oxid-esales" }}organisation: {{ print $org }}
# {{ $name := "graphql-storefront" }}name: {{ print $name }}
# {{ $group := "basket_2" }}group: {{ print $group }}
codeception:
    title: '{{ print $order }}-{{ print $name }}'
    configuration: '/var/www/vendor/{{ print $org }}/{{ print $name }}/tests/codeception.yml'
    additional_options: '--bootstrap=/var/www/source/bootstrap.php -g {{ print $group }} --coverage-xml=/var/www/coverage_codeception_{{ print $group }}.xml'
    output:
        prefix: 'codeception_artifacts_{{ print $group }}'
    logfile:
        prefix: 'codeception-{{ print $group }}'
    coverage:
        path: 'source/coverage_codeception_{{ print $group }}.xml'
        prefix: 'coverage-reports-{{ print $group }}'
