services:
  _defaults:
    autowire: true
    public: false

  OxidEsales\GraphQL\Storefront\Customer\Infrastructure\Customer:
    public: true

  OxidEsales\GraphQL\Storefront\Customer\Infrastructure\CustomerRegisterFactory:

  OxidEsales\GraphQL\Storefront\Customer\Infrastructure\PasswordInterface:
    class: OxidEsales\GraphQL\Storefront\Customer\Infrastructure\Password
    arguments:
      $inputValidator: '@=service("OxidEsales\\Eshop\\Core\\Registry").getInputValidator()'

  OxidEsales\GraphQL\Storefront\Customer\Infrastructure\RepositoryInterface:
    class: OxidEsales\GraphQL\Storefront\Customer\Infrastructure\Repository
    public: true
