services:
  _defaults:
    autowire: true
    public: false

  OxidEsales\GraphQL\Storefront\Review\Service\ActivityService:
    public: true

  OxidEsales\GraphQL\Storefront\Review\Service\RelationService:
    public: true

  OxidEsales\GraphQL\Storefront\Review\Service\Review:
    public: true

  OxidEsales\GraphQL\Storefront\Review\Service\ReviewInputValidatorInterface:
    class: OxidEsales\GraphQL\Storefront\Review\Service\ReviewInputValidator

  OxidEsales\GraphQL\Storefront\Review\Infrastructure\ReviewFactoryInterface:
    class: OxidEsales\GraphQL\Storefront\Review\Infrastructure\ReviewFactory

  OxidEsales\GraphQL\Storefront\Review\Service\Reviewer:
    public: true
