imports:
  - { resource: Controller/services.yaml }
  - { resource: Infrastructure/services.yaml }
  - { resource: Service/services.yaml }

services:
  _defaults:
    autowire: true
    public: false

  OxidEsales\Storefront\Core\Registry:
    class: OxidEsales\Eshop\Core\Registry
    public: true
