services:
  _defaults:
    autowire: true
    public: false

  OxidEsales\GraphQL\Storefront\Voucher\Infrastructure\Repository:
    public: true

  OxidEsales\GraphQL\Storefront\Voucher\Infrastructure\Voucher:
    public: true
