services:
  _defaults:
    autowire: true
    public: false

  OxidEsales\GraphQL\Storefront\Content\Service\Content:
    public: true

  OxidEsales\GraphQL\Storefront\Content\Service\RelationService:
    public: true
