services:
  _defaults:
    autowire: true
    public: false

  OxidEsales\GraphQL\Storefront\Address\Infrastructure\DeliveryAddressFactory:
    public: true

  OxidEsales\GraphQL\Storefront\Address\Infrastructure\InvoiceAddressFactory:
    public: true
