services:
  _defaults:
    autowire: true
    public: false

  OxidEsales\GraphQL\Storefront\Address\Service\DeliveryAddress:
    public: true

  OxidEsales\GraphQL\Storefront\Address\Infrastructure\DeliveryAddressFactoryInterface:
    class: OxidEsales\GraphQL\Storefront\Address\Infrastructure\DeliveryAddressFactory

  OxidEsales\GraphQL\Storefront\Address\Service\DeliveryAddressRelations:
    public: true

  OxidEsales\GraphQL\Storefront\Address\Infrastructure\InvoiceAddressFactoryInterface:
    class: OxidEsales\GraphQL\Storefront\Address\Infrastructure\InvoiceAddressFactory

  OxidEsales\GraphQL\Storefront\Address\Service\InvoiceAddress:
    public: true

  OxidEsales\GraphQL\Storefront\Address\Service\InvoiceAddressRelations:
    public: true
