name: Auto trigger on PR to 7.1.x*

on:
    pull_request:
        branches:
            - 'b-7.1.x**'

jobs:
    pull_module:
        uses: oxid-eSales/github-actions/.github/workflows/call-universal_test_workflow.yml@v4
        with:
            testplan: '~/defaults/7.1.x.yml,~/defaults/php8.2_mysql8.0_only.yml,~/graphql-storefront.yml'
            runs_on: '"ubuntu-latest"'
            defaults: 'v4'
            plan_folder: '.github/oxid-esales'
        secrets:
            DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
            DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
            CACHE_ENDPOINT: ${{ secrets.CACHE_ENDPOINT }}
            CACHE_ACCESS_KEY: ${{ secrets.CACHE_ACCESS_KEY }}
            CACHE_SECRET_KEY: ${{ secrets.CACHE_SECRET_KEY }}
            enterprise_github_token: ${{ secrets.enterprise_github_token }}
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
            SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

    push_module_ee:
        if: false
        runs-on: ubuntu-latest
        steps:
            - name: Trigger EE workflow and wait for results
              uses: convictional/trigger-workflow-and-wait@v1.6.5
              with:
                  owner: oxid-esales
                  repo: module-workflows
                  github_user: ${{ secrets.CI_USER }}
                  github_token: ${{ secrets.GH_CI_JENKINS_TOKEN }}
                  workflow_file_name: storefront_workflow.yml
                  ref: "b-7.1.x"
                  client_payload: "{\"php\": \"8.1\", \"mysql\": \"5.7\", \"edition\": \"ee\", \"ref\": \"${{ github.ref_name }}\"}"
