name: Schedule for storefront actions

on:
    schedule:
        - cron: '0 15 * * 0'

jobs:
    twig_php_80:
        name: 'Php-8.0-Mysql-5.7'
        uses: ./.github/workflows/development.yml
        secrets: inherit
        with:
            php: '8.0'
            mysql: '5.7.37'
    twig_php_81:
        name: 'Php-8.1-Mysql-8.0'
        uses: ./.github/workflows/development.yml
        secrets: inherit
        with:
            php: '8.1'
            mysql: '8.0'
