name: Schedule for storefront actions

on:
    schedule:
        - cron: '0 15 * * 0'

jobs:
    twig_php_80:
        runs-on: ubuntu-latest
        steps:
            - name: run full twig development workflow
              uses: convictional/trigger-workflow-and-wait@v1.6.5
              with:
                  owner: oxid-esales
                  repo: graphql-storefront
                  github_user: ${{ secrets.CI_USER }}
                  github_token: ${{ secrets.GH_CI_JENKINS_TOKEN }}
                  workflow_file_name: development.yml
                  ref: ${{ github.ref_name }}
                  client_payload:  '{"php": "8.0", "mysql": "5.7.37", "module_codecept_test_group": "address", "edition": "ce", "sonarcloud": false}'
    twig_php_81:
        runs-on: ubuntu-latest
        steps:
            - name: run full twig development workflow
              uses: convictional/trigger-workflow-and-wait@v1.6.5
              with:
                  owner: oxid-esales
                  repo: graphql-storefront
                  github_user: ${{ secrets.CI_USER }}
                  github_token: ${{ secrets.GH_CI_JENKINS_TOKEN }}
                  workflow_file_name: development.yml
                  ref: ${{ github.ref_name }}
                  client_payload:  '{"php": "8.1", "mysql": "8.0", "module_codecept_test_group": "address", "edition": "ce", "sonarcloud": false}'
