name: Schedule for storefront actions

on:
    schedule:
        - cron: '0 15 * * 0'

jobs:
    twig_php_80_ce:
        name: 'Php-8.0-Mysql-5.7'
        uses: ./.github/workflows/development.yml
        secrets: inherit
        with:
            php: '8.0'
            mysql: '5.7.37'
    twig_php_81_pe:
        runs-on: ubuntu-latest
        steps:
            - name: Trigger PE workflow and wait for results
              uses: convictional/trigger-workflow-and-wait@v1.6.5
              with:
                  owner: oxid-esales
                  repo: module-workflows
                  github_user: ${{ secrets.CI_USER }}
                  github_token: ${{ secrets.GH_CI_JENKINS_TOKEN }}
                  workflow_file_name: storefront_workflow.yml
                  ref: "b-7.0.x"
                  client_payload: "{\"php\": \"8.1\", \"mysql\": \"8.0\", \"edition\": \"pe\", \"ref\": \"${{ github.ref_name }}\"}"
    twig_php_81_ee:
        runs-on: ubuntu-latest
        steps:
            - name: Trigger EE workflow and wait for results
              uses: convictional/trigger-workflow-and-wait@v1.6.5
              with:
                  owner: oxid-esales
                  repo: module-workflows
                  github_user: ${{ secrets.CI_USER }}
                  github_token: ${{ secrets.GH_CI_JENKINS_TOKEN }}
                  workflow_file_name: storefront_workflow.yml
                  ref: "b-7.0.x"
                  client_payload: "{\"php\": \"8.1\", \"mysql\": \"8.0\", \"edition\": \"ee\", \"ref\": \"${{ github.ref_name }}\"}"
