name: schedule

on:
    schedule:
        - cron: '47 4 */7 * *'

jobs:
    call_matrix:
        uses: oxid-eSales/github-actions/.github/workflows/call-universal_test_workflow.yml@v4
        with:
            testplan: '~/defaults/7.1.x.yml,~/defaults/php8.1_mysql8.0_only.yml,~/defaults/php8.2_mysql8.0_only.yml,~/defaults/php8.1_mysql5.7_only.yml,~/graphql-storefront.yml'
            runs_on: '"ubuntu-latest"'
            defaults: 'v4'
            plan_folder: '.github/oxid-esales'
        secrets:
            DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
            DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
            CACHE_ENDPOINT: ${{ secrets.CACHE_ENDPOINT }}
            CACHE_ACCESS_KEY: ${{ secrets.CACHE_ACCESS_KEY }}
            CACHE_SECRET_KEY: ${{ secrets.CACHE_SECRET_KEY }}
            enterprise_github_token: ${{ secrets.enterprise_github_token }}
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
            SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
