name: Trigger workflow for storefront actions

on:
    pull_request:
    push:
        branches:
            - b-7.0.x

jobs:
    twig:
        runs-on: ubuntu-latest
        steps:
            - name: run full twig development workflow
              uses: convictional/trigger-workflow-and-wait@v1.6.5
              with:
                  owner: oxid-esales
                  repo: graphql-storefront
                  github_user: ${{ secrets.CI_USER }}
                  github_token: ${{ secrets.GH_CI_JENKINS_TOKEN }}
                  workflow_file_name: development.yml
                  ref: ${{ github.ref_name }}
                  client_payload:  '{"php": "8.0", "mysql": "5.7.37", "module_codecept_test_group": "all", "edition": "pe"}'
